[package]
name = "advent_of_code_solutions"
version = "0.1.0"
authors = ["Nick Hultz <nhultz328@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
itertools = "0.8"
chrono = "0.4"
anyhow = "1.0"
thiserror = "1.0"
